run:
  timeout: 2m

linters:
  enable:
    # enabled by default
    # https://golangci-lint.run/usage/linters/
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    # project additions
    # keep this list alphabetically sorted
    - bodyclose
    - goconst
    # - gofmt  -- goimports contains this
    - goimports
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/61qt/go-workwx
  misspell:
    locale: US
  nakedret:
    max-func-lines: 1
