// Code generated by sdkcodegen; DO NOT EDIT.

package workwx

// KfAccount 客服账号
type KfAccount struct {
	// OpenKfID 客服账号ID
	OpenKfID string `json:"open_kfid"`
	// Name 客服名称
	Name string `json:"name"`
	// Avatar 客服头像URL
	Avatar string `json:"avatar"`
	// ManagePrivilege 当前调用接口的应用身份，是否有该客服账号的管理权限（编辑客服账号信息、分配会话和收发消息）。组件应用不返回此字段
	ManagePrivilege bool `json:"manage_privilege,omitempty"`
}
